import type { BlockDef, BlockPin, McuPinMap } from "./types";

const P = (name: string, desc: string, kind: BlockPin["kind"] = "digital"): BlockPin => ({ name, desc, kind });
const VCC = P("VCC", "3.3V supply", "power");
const GND = P("GND", "Ground", "gnd");
const I2C_PINS = [VCC, GND, P("SDA", "I2C data", "bus"), P("SCL", "I2C clock", "bus")];

type Partial_ = Omit<BlockDef, "voltage" | "sleepUa" | "vendor" | "massG"> & Partial<Pick<BlockDef, "voltage" | "sleepUa" | "vendor" | "massG">>;
const def = (b: Partial_): BlockDef => ({
  voltage: { min: 3.0, max: 3.6 },
  sleepUa: 5,
  vendor: "Robu.in",
  massG: Math.max(1, Math.round((b.size.w * b.size.d * b.size.h) / 600)),
  ...b,
});

const mcuPins = (m: McuPinMap): BlockPin[] => [
  P("3V3", "3.3V output", "power"),
  P("5V", "5V input (USB / VIN)", "power"),
  P("GND", "Ground", "gnd"),
  ...m.adc.slice(0, 2).map((n) => P(`GPIO${n}`, "Analog in (ADC)", "analog")),
  P(`GPIO${m.i2c.sda}`, "I2C SDA (default)", "bus"),
  P(`GPIO${m.i2c.scl}`, "I2C SCL (default)", "bus"),
  ...m.gpio.slice(0, 3).map((n) => P(`GPIO${n}`, "Digital I/O")),
];

const mcu = (
  b: Pick<BlockDef, "id" | "name" | "subtitle" | "description" | "size" | "priceInr" | "activeMa" | "sleepUa" | "specs"> & { pinmap: McuPinMap; tags?: string[] },
): BlockDef =>
  def({
    ...b,
    role: "Main Controller",
    category: "mcu",
    group: "Compute",
    tags: ["mcu", "wifi", "ble", ...(b.tags ?? [])],
    mount: "internal",
    port: { shape: "rect", w: 9.6, h: 3.8 },
    iface: "mcu",
    signals: [],
    voltage: { min: 3.3, max: 5.5 },
    supplyMa: 500,
    pins: mcuPins(b.pinmap),
    color: "#5B7CFA",
    icon: "cpu",
  });

export const BLOCKS: BlockDef[] = [
  // ───────── Compute ─────────
  mcu({
    id: "esp32_devkit",
    name: "ESP32",
    subtitle: "Wi-Fi • Bluetooth",
    description: "ESP32-WROOM dev module. The default brain: plenty of pins, Wi-Fi and Bluetooth, runs MicroPython.",
    size: { w: 52, d: 28, h: 8 },
    priceInr: 450,
    activeMa: 80,
    sleepUa: 150,
    pinmap: {
      i2c: { sda: 21, scl: 22 },
      adc: [34, 35, 32, 33, 36, 39],
      gpio: [4, 5, 13, 14, 16, 17, 18, 19, 23, 25, 26, 27],
      i2s: { bclk: 26, ws: 25, din: 33, dout: 27 },
      uart: { tx: 17, rx: 16 },
      spi: { sck: 18, mosi: 23 },
    },
    specs: [
      ["MCU", "ESP32 (Dual Core, 240MHz)"],
      ["Wireless", "Wi-Fi + Bluetooth 4.2"],
      ["Operating Voltage", "3.3V"],
      ["Recommended Input", "5V (via USB-C)"],
      ["Digital I/O Pins", "30"],
      ["Analog Input Pins", "18 (12-bit ADC)"],
    ],
  }),
  mcu({
    id: "esp32_s3_devkit",
    name: "ESP32-S3",
    subtitle: "Wi-Fi • BLE 5 • AI",
    description: "Faster dual-core ESP32-S3 with native USB and more memory. Pick it for audio or heavier processing.",
    size: { w: 57, d: 28, h: 8 },
    priceInr: 720,
    activeMa: 95,
    sleepUa: 120,
    tags: ["audio_capable"],
    pinmap: {
      i2c: { sda: 8, scl: 9 },
      adc: [1, 2, 3, 4, 5, 6, 7],
      gpio: [10, 11, 12, 13, 14, 21, 38, 39, 40, 41, 42, 47],
      i2s: { bclk: 15, ws: 16, din: 17, dout: 18 },
      uart: { tx: 43, rx: 44 },
      spi: { sck: 36, mosi: 35 },
    },
    specs: [
      ["MCU", "ESP32-S3 (Dual Core, 240MHz)"],
      ["Wireless", "Wi-Fi + Bluetooth LE 5"],
      ["Operating Voltage", "3.3V"],
      ["Recommended Input", "5V (via USB-C)"],
      ["Digital I/O Pins", "36"],
      ["Flash / PSRAM", "8MB / 2MB"],
    ],
  }),
  mcu({
    id: "esp32_c3_supermini",
    name: "ESP32-C3 Mini",
    subtitle: "Wi-Fi • BLE 5 • Tiny",
    description: "Thumbnail-sized ESP32-C3 board. Fewer pins, low power, ideal for small battery devices.",
    size: { w: 22.5, d: 18, h: 5 },
    priceInr: 290,
    activeMa: 60,
    sleepUa: 45,
    tags: ["tiny", "low_power"],
    pinmap: {
      i2c: { sda: 8, scl: 9 },
      adc: [0, 1, 2, 3, 4],
      gpio: [5, 6, 7, 10, 20, 21],
      i2s: { bclk: 5, ws: 6, din: 7, dout: 10 },
      uart: { tx: 21, rx: 20 },
      spi: { sck: 4, mosi: 6 },
    },
    specs: [
      ["MCU", "ESP32-C3 (RISC-V, 160MHz)"],
      ["Wireless", "Wi-Fi + Bluetooth LE 5"],
      ["Operating Voltage", "3.3V"],
      ["Recommended Input", "5V (via USB-C)"],
      ["Digital I/O Pins", "11"],
      ["Analog Input Pins", "5 (12-bit ADC)"],
    ],
  }),
  mcu({
    id: "xiao_esp32s3",
    name: "XIAO ESP32-S3",
    subtitle: "Wi-Fi • BLE 5 • Tiny",
    description: "Seeed XIAO: the S3 in a 21 mm board with a battery charger built in. Best for small audio devices.",
    size: { w: 21, d: 17.8, h: 5 },
    priceInr: 890,
    activeMa: 85,
    sleepUa: 14,
    tags: ["tiny", "low_power", "audio_capable", "onboard_charger"],
    pinmap: {
      i2c: { sda: 5, scl: 6 },
      adc: [1, 2, 3, 4],
      gpio: [7, 8, 9, 43, 44],
      i2s: { bclk: 7, ws: 8, din: 9, dout: 44 },
      uart: { tx: 43, rx: 44 },
      spi: { sck: 7, mosi: 9 },
    },
    specs: [
      ["MCU", "ESP32-S3 (Dual Core, 240MHz)"],
      ["Wireless", "Wi-Fi + Bluetooth LE 5"],
      ["Operating Voltage", "3.3V"],
      ["Battery", "On-board LiPo charging"],
      ["Digital I/O Pins", "11"],
      ["Flash / PSRAM", "8MB / 8MB"],
    ],
  }),

  // ───────── Input ─────────
  def({
    id: "soil_moisture",
    name: "Soil Moisture Sensor",
    subtitle: "Analog (ADC)",
    role: "Capacitive probe",
    category: "sensor",
    group: "Input",
    description: "Capacitive soil probe. Does not corrode like the cheap resistive kind.",
    tags: ["soil_moisture", "plant", "moisture"],
    size: { w: 22, d: 98, h: 3 },
    mount: "bottom_external",
    cutout: { shape: "rect", w: 24, h: 4 },
    iface: "adc",
    signals: ["AOUT"],
    activeMa: 5,
    specs: [["Type", "Capacitive v1.2"], ["Output", "Analog 0–3.0V"], ["Supply", "3.3–5.5V"], ["Dimensions", "98 × 22 × 3 mm"]],
    pins: [VCC, GND, P("AOUT", "Analog output", "analog")],
    priceInr: 120,
    color: "#4E9A47",
    icon: "droplet",
    driver: {
      setup: ["soil = machine.ADC(machine.Pin({AOUT}))", "soil.atten(machine.ADC.ATTN_11DB)"],
      read: {
        name: "read_soil",
        body: ["raw = soil.read()", "# 2800 is bone dry, 1200 is in water. Calibrate for your probe.", "pct = max(0, min(100, int((2800 - raw) * 100 / 1600)))", "return pct"],
        fields: ["moisture"],
      },
    },
  }),
  def({
    id: "dht22",
    name: "DHT22",
    subtitle: "Temperature • Humidity",
    role: "Climate sensor",
    category: "sensor",
    group: "Input",
    description: "Air temperature and humidity on a single data pin.",
    tags: ["temperature", "humidity"],
    size: { w: 20, d: 15, h: 8 },
    mount: "internal",
    iface: "gpio",
    signals: ["DATA"],
    activeMa: 2,
    specs: [["Range", "-40–80°C, 0–100% RH"], ["Accuracy", "±0.5°C, ±2% RH"], ["Interface", "Single-wire digital"], ["Supply", "3.3–6V"]],
    pins: [VCC, GND, P("DATA", "Data")],
    priceInr: 180,
    color: "#E8833A",
    icon: "thermometer",
    driver: {
      imports: ["import dht"],
      setup: ["climate = dht.DHT22(machine.Pin({DATA}))"],
      read: { name: "read_climate", body: ["climate.measure()", "return climate.temperature(), climate.humidity()"], fields: ["temperature", "humidity"] },
    },
  }),
  def({
    id: "sht31",
    name: "Temperature Sensor",
    subtitle: "I2C (SHT31)",
    role: "Precise climate sensor",
    category: "sensor",
    group: "Input",
    description: "Lab-grade temperature and humidity over I2C.",
    tags: ["temperature", "humidity", "precise"],
    size: { w: 13, d: 10, h: 3 },
    mount: "internal",
    iface: "i2c",
    signals: ["SDA", "SCL"],
    i2cAddr: "0x44",
    activeMa: 1.5,
    specs: [["Accuracy", "±0.2°C, ±2% RH"], ["Interface", "I2C (0x44)"], ["Supply", "2.4–5.5V"]],
    pins: I2C_PINS,
    priceInr: 260,
    color: "#E8833A",
    icon: "thermometer",
    driver: {
      setup: [],
      read: {
        name: "read_climate",
        body: ["i2c.writeto(0x44, b'\\x24\\x00')", "time.sleep_ms(20)", "d = i2c.readfrom(0x44, 6)", "temp = -45 + 175 * ((d[0] << 8) | d[1]) / 65535", "hum = 100 * ((d[3] << 8) | d[4]) / 65535", "return round(temp, 1), round(hum, 1)"],
        fields: ["temperature", "humidity"],
      },
    },
  }),
  def({
    id: "ds18b20",
    name: "Waterproof Temp Probe",
    subtitle: "DS18B20 • 1-Wire",
    role: "Liquid / soil temperature",
    category: "sensor",
    group: "Input",
    description: "Sealed steel probe on a cable, for soil, water or outdoor temperature.",
    tags: ["temperature", "waterproof", "outdoor"],
    size: { w: 30, d: 6, h: 6 },
    mount: "internal",
    iface: "gpio",
    signals: ["DATA"],
    activeMa: 1.5,
    specs: [["Range", "-55–125°C"], ["Accuracy", "±0.5°C"], ["Interface", "1-Wire"], ["Cable", "1 m"]],
    pins: [VCC, GND, P("DATA", "1-Wire data")],
    priceInr: 140,
    color: "#E8833A",
    icon: "thermometer",
    driver: {
      imports: ["import onewire", "import ds18x20"],
      setup: ["probe = ds18x20.DS18X20(onewire.OneWire(machine.Pin({DATA})))", "probe_roms = probe.scan()"],
      read: { name: "read_probe", body: ["probe.convert_temp()", "time.sleep_ms(750)", "return round(probe.read_temp(probe_roms[0]), 1) if probe_roms else None"], fields: ["probe_temperature"] },
    },
  }),
  def({
    id: "bh1750",
    name: "Light Sensor",
    subtitle: "I2C (BH1750)",
    role: "Ambient light",
    category: "sensor",
    group: "Input",
    description: "Measures brightness in lux.",
    tags: ["light", "lux"],
    size: { w: 18.5, d: 14, h: 3 },
    mount: "front",
    cutout: { shape: "circle", w: 5, h: 5 },
    iface: "i2c",
    signals: ["SDA", "SCL"],
    i2cAddr: "0x23",
    activeMa: 0.2,
    specs: [["Range", "1–65535 lux"], ["Interface", "I2C (0x23)"], ["Supply", "3–5V"]],
    pins: I2C_PINS,
    priceInr: 110,
    color: "#E0B13C",
    icon: "sun",
    driver: {
      setup: [],
      read: { name: "read_light", body: ["i2c.writeto(0x23, b'\\x20')", "time.sleep_ms(180)", "d = i2c.readfrom(0x23, 2)", "return int(((d[0] << 8) | d[1]) / 1.2)"], fields: ["lux"] },
    },
  }),
  def({
    id: "mpu6050",
    name: "Motion Sensor",
    subtitle: "I2C (MPU6050)",
    role: "Accelerometer + gyro",
    category: "sensor",
    group: "Input",
    description: "Six-axis motion: detects tilt, taps, shakes and orientation.",
    tags: ["motion", "accelerometer", "tilt", "orientation"],
    size: { w: 21, d: 16, h: 3 },
    mount: "internal",
    iface: "i2c",
    signals: ["SDA", "SCL"],
    i2cAddr: "0x68",
    activeMa: 3.8,
    specs: [["Axes", "3 accel + 3 gyro"], ["Interface", "I2C (0x68)"], ["Supply", "3–5V"]],
    pins: I2C_PINS,
    priceInr: 150,
    color: "#8A6FE8",
    icon: "move-3d",
    driver: {
      imports: ["import struct"],
      setup: ["i2c.writeto_mem(0x68, 0x6B, b'\\x00')  # wake the MPU6050"],
      read: { name: "read_motion", body: ["ax, ay, az = struct.unpack('>hhh', i2c.readfrom_mem(0x68, 0x3B, 6))", "return ax / 16384, ay / 16384, az / 16384"], fields: ["ax", "ay", "az"] },
    },
  }),
  def({
    id: "pir",
    name: "Presence Sensor",
    subtitle: "PIR • Digital",
    role: "Motion detection",
    category: "sensor",
    group: "Input",
    description: "Small PIR sensor that fires when a person or pet moves nearby.",
    tags: ["presence", "pir", "motion_detect"],
    size: { w: 10, d: 10, h: 12 },
    protrude: 4,
    mount: "front",
    cutout: { shape: "circle", w: 9, h: 9 },
    iface: "gpio",
    signals: ["OUT"],
    activeMa: 0.05,
    specs: [["Type", "AM312 mini PIR"], ["Range", "3–5 m"], ["Output", "Digital high on motion"]],
    pins: [VCC, GND, P("OUT", "Motion output")],
    priceInr: 90,
    color: "#8A6FE8",
    icon: "radar",
    driver: { setup: ["pir = machine.Pin({OUT}, machine.Pin.IN)"], read: { name: "read_presence", body: ["return pir.value() == 1"], fields: ["presence"] } },
  }),
  def({
    id: "mic_inmp441",
    name: "Microphone",
    subtitle: "I2S MEMS (INMP441)",
    role: "Voice capture",
    category: "audio",
    group: "Input",
    description: "Digital MEMS microphone with clean audio for voice notes and sound detection.",
    tags: ["microphone", "audio_in", "voice"],
    size: { w: 14, d: 14, h: 3 },
    mount: "front",
    cutout: { shape: "circle", w: 2, h: 2 },
    iface: "i2s_in",
    signals: ["BCLK", "WS", "SD"],
    activeMa: 1.4,
    specs: [["Type", "Omnidirectional MEMS"], ["Interface", "I2S"], ["SNR", "61 dB"], ["Supply", "1.8–3.3V"]],
    pins: [VCC, GND, P("SCK", "I2S bit clock", "bus"), P("WS", "I2S word select", "bus"), P("SD", "I2S data out", "bus")],
    priceInr: 190,
    color: "#D95C8A",
    icon: "mic",
    driver: {
      imports: ["from machine import I2S"],
      setup: ["mic = I2S(0, sck=machine.Pin({BCLK}), ws=machine.Pin({WS}), sd=machine.Pin({SD}), mode=I2S.RX, bits=16, format=I2S.MONO, rate=16000, ibuf=20000)"],
      read: { name: "record_chunk", body: ["buf = bytearray(4096)", "n = mic.readinto(buf)", "return buf[:n]"], fields: ["audio"] },
    },
  }),
  def({
    id: "button",
    name: "Button",
    subtitle: "Digital Input",
    role: "User input",
    category: "input",
    group: "Input",
    description: "Tactile push button with a cap that pokes through the enclosure.",
    tags: ["button", "user_input"],
    size: { w: 12, d: 12, h: 5 },
    round: true,
    mount: "front",
    cutout: { shape: "circle", w: 7.5, h: 7.5 },
    iface: "gpio",
    signals: ["SIG"],
    activeMa: 0,
    sleepUa: 0,
    specs: [["Type", "12 mm tactile"], ["Travel", "0.3 mm"], ["Wiring", "Active low, internal pull-up"]],
    pins: [P("SIG", "Signal"), GND],
    priceInr: 15,
    color: "#C9AE8C",
    icon: "circle-dot",
    driver: { setup: ["button = machine.Pin({SIG}, machine.Pin.IN, machine.Pin.PULL_UP)"], read: { name: "button_pressed", body: ["return button.value() == 0"], fields: ["pressed"] } },
  }),
  def({
    id: "rotary_encoder",
    name: "Rotary Knob",
    subtitle: "Encoder + push",
    role: "Dial input",
    category: "input",
    group: "Input",
    description: "Clicky dial with a push switch, for setting values and scrolling menus.",
    tags: ["knob", "dial", "encoder", "user_input"],
    size: { w: 14, d: 12, h: 20 },
    protrude: 13,
    mount: "front",
    cutout: { shape: "circle", w: 7.2, h: 7.2 },
    iface: "gpio",
    signals: ["CLK", "DT", "SW"],
    activeMa: 0.5,
    specs: [["Type", "EC11, 20 detents"], ["Shaft", "6 mm D-shaft"], ["Switch", "Push to select"]],
    pins: [VCC, GND, P("CLK", "Encoder A"), P("DT", "Encoder B"), P("SW", "Push switch")],
    priceInr: 70,
    color: "#C9AE8C",
    icon: "rotate-cw",
    driver: {
      setup: ["enc_clk = machine.Pin({CLK}, machine.Pin.IN, machine.Pin.PULL_UP)", "enc_dt = machine.Pin({DT}, machine.Pin.IN, machine.Pin.PULL_UP)", "enc_sw = machine.Pin({SW}, machine.Pin.IN, machine.Pin.PULL_UP)", "enc_last = enc_clk.value()"],
      read: { name: "read_knob", body: ["global enc_last", "step = 0", "now = enc_clk.value()", "if now != enc_last and now == 0:", "    step = 1 if enc_dt.value() else -1", "enc_last = now", "return step, enc_sw.value() == 0"], fields: ["step", "knob_pressed"] },
    },
  }),

  // ───────── Output ─────────
  def({
    id: "oled_096",
    name: "OLED Display",
    subtitle: 'I2C 0.96"',
    role: "Status screen",
    category: "display",
    group: "Output",
    description: "Crisp 128×64 monochrome OLED for readings and status.",
    tags: ["display", "screen", "oled"],
    size: { w: 27, d: 27, h: 4 },
    mount: "front",
    cutout: { shape: "rect", w: 25, h: 14 },
    iface: "i2c",
    signals: ["SDA", "SCL"],
    i2cAddr: "0x3C",
    activeMa: 15,
    specs: [["Resolution", "128 × 64"], ["Driver", "SSD1306"], ["Interface", "I2C (0x3C)"], ["Supply", "3.3–5V"]],
    pins: I2C_PINS,
    priceInr: 160,
    color: "#3B82C4",
    icon: "monitor",
    driver: {
      imports: ["import ssd1306  # mpremote mip install ssd1306"],
      setup: ["oled = ssd1306.SSD1306_I2C(128, 64, i2c)"],
      act: { name: "show", body: ["oled.fill(0)", "for row, line in enumerate(str(value).split('\\n')[:6]):", "    oled.text(line, 0, row * 10)", "oled.show()"] },
    },
  }),
  def({
    id: "tft_154",
    name: "Color Display",
    subtitle: 'SPI 1.54" IPS',
    role: "Colour screen",
    category: "display",
    group: "Output",
    description: "240×240 colour IPS screen for richer interfaces.",
    tags: ["display", "screen", "color_display"],
    size: { w: 32, d: 44, h: 4 },
    mount: "front",
    cutout: { shape: "rect", w: 28, h: 28 },
    iface: "spi",
    signals: ["SCK", "MOSI", "CS", "DC"],
    activeMa: 40,
    specs: [["Resolution", "240 × 240"], ["Driver", "ST7789"], ["Interface", "SPI"], ["Supply", "3.3V"]],
    pins: [VCC, GND, P("SCK", "SPI clock", "bus"), P("MOSI", "SPI data", "bus"), P("CS", "Chip select"), P("DC", "Data / command")],
    priceInr: 390,
    color: "#3B82C4",
    icon: "monitor-smartphone",
    driver: {
      imports: ["import st7789  # mpremote mip install st7789"],
      setup: ["spi = machine.SPI(1, baudrate=40000000, sck=machine.Pin({SCK}), mosi=machine.Pin({MOSI}))", "tft = st7789.ST7789(spi, 240, 240, cs=machine.Pin({CS}, machine.Pin.OUT), dc=machine.Pin({DC}, machine.Pin.OUT))"],
      act: { name: "show", body: ["tft.fill(0)", "tft.text(str(value), 10, 10)"] },
    },
  }),
  def({
    id: "led",
    name: "LED",
    subtitle: "Digital Output",
    role: "Status light",
    category: "output",
    group: "Output",
    description: "Single status LED with its resistor.",
    tags: ["led", "status_light"],
    size: { w: 5, d: 5, h: 5 },
    round: true,
    mount: "front",
    cutout: { shape: "circle", w: 3.2, h: 3.2 },
    iface: "gpio",
    signals: ["SIG"],
    activeMa: 8,
    sleepUa: 0,
    specs: [["Type", "3 mm diffused"], ["Current", "8 mA with 220Ω"], ["Wiring", "Active high"]],
    pins: [P("SIG", "Anode via 220Ω"), GND],
    priceInr: 10,
    color: "#55B04A",
    icon: "lightbulb",
    driver: { setup: ["led = machine.Pin({SIG}, machine.Pin.OUT)"], act: { name: "set_led", body: ["led.value(1 if value else 0)"] } },
  }),
  def({
    id: "rgb_led",
    name: "RGB Light Ring",
    subtitle: "WS2812 • 8 pixels",
    role: "Colour feedback",
    category: "output",
    group: "Output",
    description: "Ring of eight addressable RGB LEDs for glow, progress and alerts.",
    tags: ["rgb", "light", "neopixel", "glow"],
    size: { w: 32, d: 32, h: 3 },
    round: true,
    hole: 20,
    mount: "front",
    iface: "gpio",
    signals: ["DIN"],
    voltage: { min: 3.3, max: 5.3 },
    activeMa: 60,
    sleepUa: 600,
    specs: [["Pixels", "8 × WS2812B"], ["Diameter", "32 mm"], ["Supply", "3.3–5V"], ["Shows through", "Thin wall, no cutout"]],
    pins: [P("5V", "Supply", "power"), GND, P("DIN", "Data in")],
    priceInr: 130,
    color: "#D95C8A",
    icon: "sparkles",
    driver: {
      imports: ["import neopixel"],
      setup: ["ring = neopixel.NeoPixel(machine.Pin({DIN}), 8)"],
      act: { name: "set_ring", body: ["# value is an (r, g, b) tuple", "ring.fill(value)", "ring.write()"] },
    },
  }),
  def({
    id: "buzzer",
    name: "Buzzer",
    subtitle: "PWM Output",
    role: "Beeps and alerts",
    category: "audio",
    group: "Output",
    description: "Passive piezo buzzer that plays tones.",
    tags: ["buzzer", "beep", "alert", "sound_out"],
    size: { w: 12, d: 12, h: 8.5 },
    mount: "internal",
    iface: "gpio",
    signals: ["SIG"],
    activeMa: 25,
    sleepUa: 0,
    specs: [["Type", "Passive piezo"], ["Drive", "PWM, 2–4 kHz"], ["Volume", "85 dB at 10 cm"]],
    pins: [P("SIG", "PWM signal"), GND],
    priceInr: 25,
    color: "#55585E",
    icon: "bell",
    driver: {
      setup: ["buzzer = machine.PWM(machine.Pin({SIG}), freq=2700, duty=0)"],
      act: { name: "beep", body: ["# value is the duration in milliseconds", "buzzer.duty(512)", "time.sleep_ms(value)", "buzzer.duty(0)"] },
    },
  }),
  def({
    id: "speaker_amp",
    name: "Speaker",
    subtitle: "I2S amp + 1W speaker",
    role: "Audio playback",
    category: "audio",
    group: "Output",
    description: "MAX98357 amplifier with a small speaker for voice prompts and audio.",
    tags: ["speaker", "audio_out", "sound_out"],
    size: { w: 28, d: 28, h: 9 },
    round: true,
    mount: "back",
    cutout: { shape: "circle", w: 20, h: 20, grille: true },
    iface: "i2s_out",
    signals: ["BCLK", "WS", "DIN"],
    voltage: { min: 3.0, max: 5.5 },
    activeMa: 180,
    sleepUa: 2,
    specs: [["Amp", "MAX98357A, 3W class D"], ["Speaker", "28 mm, 8Ω 1W"], ["Interface", "I2S"]],
    pins: [P("VIN", "Supply", "power"), GND, P("BCLK", "I2S bit clock", "bus"), P("LRC", "I2S word select", "bus"), P("DIN", "I2S data in", "bus")],
    priceInr: 310,
    color: "#55585E",
    icon: "volume-2",
    driver: {
      imports: ["from machine import I2S"],
      setup: ["speaker = I2S(1, sck=machine.Pin({BCLK}), ws=machine.Pin({WS}), sd=machine.Pin({DIN}), mode=I2S.TX, bits=16, format=I2S.MONO, rate=16000, ibuf=20000)"],
      act: { name: "play", body: ["# value is 16-bit mono PCM bytes at 16 kHz", "speaker.write(value)"] },
    },
  }),
  def({
    id: "vibration_motor",
    name: "Vibration Motor",
    subtitle: "Haptic • PWM",
    role: "Haptic feedback",
    category: "output",
    group: "Output",
    description: "Coin vibration motor with a driver transistor, for silent buzzes.",
    tags: ["haptic", "vibration"],
    size: { w: 10, d: 10, h: 3 },
    round: true,
    mount: "internal",
    iface: "gpio",
    signals: ["SIG"],
    activeMa: 75,
    sleepUa: 0,
    specs: [["Type", "10 mm coin ERM"], ["Drive", "Transistor module"], ["Supply", "3–3.7V"]],
    pins: [VCC, GND, P("SIG", "Drive signal")],
    priceInr: 60,
    color: "#8A6FE8",
    icon: "vibrate",
    driver: { setup: ["motor = machine.Pin({SIG}, machine.Pin.OUT)"], act: { name: "buzz", body: ["motor.value(1)", "time.sleep_ms(value)", "motor.value(0)"] } },
  }),

  // ───────── Connect ─────────
  def({
    id: "usb_c",
    name: "USB-C Module",
    subtitle: "Charging & Data",
    role: "5V input",
    category: "connectivity",
    group: "Connect",
    description: "Panel USB-C breakout, for when the port needs to sit away from the main board.",
    tags: ["usb", "usb_power"],
    size: { w: 14, d: 12, h: 4 },
    mount: "internal",
    port: { shape: "rect", w: 9.6, h: 3.8 },
    iface: "power",
    signals: [],
    voltage: { min: 4.5, max: 5.5 },
    activeMa: 0,
    sleepUa: 0,
    supplyMa: 1500,
    specs: [["Connector", "USB-C receptacle"], ["Output", "5V, up to 1.5A"], ["CC resistors", "5.1kΩ fitted"]],
    pins: [P("VBUS", "5V out", "power"), GND, P("D+", "USB data", "bus"), P("D-", "USB data", "bus")],
    priceInr: 45,
    color: "#E0B13C",
    icon: "usb",
  }),
  def({
    id: "gps",
    name: "GPS Module",
    subtitle: "NEO-6M • UART",
    role: "Location",
    category: "connectivity",
    group: "Connect",
    description: "GPS receiver with a ceramic antenna for outdoor location.",
    tags: ["gps", "location", "tracking"],
    size: { w: 36, d: 26, h: 8 },
    mount: "internal",
    iface: "uart",
    signals: ["TX", "RX"],
    activeMa: 45,
    sleepUa: 11000,
    specs: [["Chip", "u-blox NEO-6M"], ["Accuracy", "2.5 m"], ["Interface", "UART 9600 baud"], ["Cold start", "~30 s outdoors"]],
    pins: [VCC, GND, P("TX", "Module transmit", "bus"), P("RX", "Module receive", "bus")],
    priceInr: 420,
    color: "#3B82C4",
    icon: "map-pin",
    driver: {
      setup: ["gps = machine.UART(1, baudrate=9600, tx={RX}, rx={TX})"],
      read: { name: "read_gps", body: ["line = gps.readline()", "# Returns one raw NMEA sentence; parse $GPGGA for latitude and longitude.", "return line.decode('ascii', 'ignore').strip() if line else None"], fields: ["nmea"] },
    },
  }),
  def({
    id: "magsafe_ring",
    name: "MagSafe Ring",
    subtitle: "Magnetic mount",
    role: "Phone attachment",
    category: "other",
    group: "Connect",
    description: "Magnet array that snaps the device onto the back of a MagSafe phone or case.",
    tags: ["magsafe", "magnetic_mount", "phone_mount"],
    size: { w: 56, d: 56, h: 1.2 },
    round: true,
    mount: "back",
    iface: "none",
    signals: [],
    activeMa: 0,
    sleepUa: 0,
    specs: [["Diameter", "56 mm outer, 46 mm inner"], ["Thickness", "1.2 mm"], ["Hold", "~800 g"], ["Fitting", "Recessed in the rear wall"]],
    pins: [],
    priceInr: 140,
    color: "#9AA0A6",
    icon: "magnet",
  }),

  def({
    id: "magsafe_charger",
    name: "MagSafe Charging Pad",
    subtitle: "Qi wireless • 7.5W",
    role: "Charges the phone",
    category: "power",
    group: "Power",
    description: "Wireless charging coil with its MagSafe magnet ring built in. Snaps to the phone and charges it. Needs the Power Bank Module.",
    tags: ["magsafe", "magnetic_mount", "phone_mount", "wireless_charging", "phone_charging"],
    size: { w: 56, d: 56, h: 5.5 },
    round: true,
    mount: "back",
    iface: "power",
    signals: [],
    voltage: { min: 4.5, max: 5.5 },
    activeMa: 0,
    sleepUa: 0,
    specs: [["Output", "Qi, up to 7.5W to an iPhone"], ["Input", "5V, up to 2A"], ["Diameter", "56 mm with magnet ring"], ["Fitting", "Against the rear wall, which must stay thin"]],
    pins: [P("5V", "5V in", "power"), GND],
    priceInr: 480,
    color: "#9AA0A6",
    icon: "zap",
  }),
  def({
    id: "powerbank_module",
    name: "Power Bank Module",
    subtitle: "IP5306 • USB-C • 5V 2A",
    role: "Charging & 5V output",
    category: "power",
    group: "Power",
    description: "Charges the battery from USB-C and boosts it to 5V at up to 2A, enough to charge a phone. Replaces the Battery Charger.",
    tags: ["charger", "usb_power", "boost_5v", "phone_charging"],
    size: { w: 25, d: 16, h: 4 },
    mount: "internal",
    port: { shape: "rect", w: 9.6, h: 3.8 },
    iface: "power",
    signals: [],
    voltage: { min: 4.5, max: 5.5 },
    activeMa: 0,
    sleepUa: 50,
    supplyMa: 2000,
    specs: [["Output", "5V, up to 2.1A"], ["Charge current", "Up to 2.1A from USB-C"], ["Protection", "Over-charge, over-discharge, short circuit"]],
    pins: [P("5V", "5V out", "power"), P("BAT+", "To battery", "power"), P("OUT+", "To load", "power"), GND],
    priceInr: 150,
    color: "#E8833A",
    icon: "zap",
  }),

  // ───────── Power ─────────
  ...([
    ["lipo_500", "Li-Po Battery 500", 500, { w: 30, d: 20, h: 5 }, 160],
    ["lipo_1000", "Li-Po Battery", 1000, { w: 48, d: 30, h: 6 }, 220],
    ["lipo_2000", "Li-Po Battery 2000", 2000, { w: 60, d: 34, h: 8 }, 340],
    ["lipo_3000", "Slim Li-Po 3000", 3000, { w: 50, d: 72, h: 6.5 }, 520],
    // Power bank cells. All three share a footprint that fits the phone-back card; only the thickness grows.
    ["lipo_5000", "Power Bank Cell 5000", 5000, { w: 56, d: 86, h: 6.5 }, 690],
    ["lipo_10000", "Power Bank Cell 10000", 10000, { w: 56, d: 86, h: 12 }, 1150],
    ["lipo_20000", "Power Bank Pack 20000", 20000, { w: 56, d: 86, h: 24 }, 2100],
  ] as const).map(([id, name, mah, size, price]) =>
    def({
      id,
      name,
      subtitle: `3.7V (${mah}mAh)`,
      role: "Rechargeable power",
      category: "power",
      group: "Power",
      description: `Rechargeable ${mah} mAh lithium-polymer cell with a protection circuit.`,
      tags: ["battery", "rechargeable"],
      size: { ...size },
      massG: Math.round(mah / 45),
      mount: "internal",
      iface: "power",
      signals: [],
      voltage: { min: 3.0, max: 4.2 },
      activeMa: 0,
      sleepUa: 2,
      capacityMah: mah,
      supplyMa: mah * 2,
      specs: [["Capacity", `${mah} mAh`], ["Voltage", "3.7V nominal, 4.2V full"], ["Protection", "Over-charge and over-discharge"], ["Connector", "JST-PH 2.0"]],
      pins: [P("BAT+", "Positive", "power"), P("BAT-", "Negative", "gnd")],
      priceInr: price,
      color: "#E0B13C",
      icon: "battery-full",
    }),
  ),
  def({
    id: "charger_tp4056",
    name: "Battery Charger",
    subtitle: "TP4056 • USB-C",
    role: "Charging & protection",
    category: "power",
    group: "Power",
    description: "Charges the Li-Po from USB-C and protects it from over-discharge.",
    tags: ["charger", "usb_power"],
    size: { w: 28, d: 17, h: 4 },
    mount: "internal",
    port: { shape: "rect", w: 9.6, h: 3.8 },
    iface: "power",
    signals: [],
    voltage: { min: 4.5, max: 5.5 },
    activeMa: 0,
    sleepUa: 3,
    supplyMa: 1000,
    specs: [["Charge current", "1A (set by resistor)"], ["Input", "5V USB-C"], ["Protection", "DW01A over-discharge at 2.5V"]],
    pins: [P("IN+", "5V in", "power"), P("BAT+", "To battery", "power"), P("OUT+", "To load", "power"), GND],
    priceInr: 60,
    color: "#E8833A",
    icon: "zap",
  }),
  def({
    id: "regulator_3v3",
    name: "Voltage Regulator",
    subtitle: "3.3V buck-boost",
    role: "Stable 3.3V rail",
    category: "power",
    group: "Power",
    description: "Holds a steady 3.3V across the whole battery range, so you use every bit of the cell.",
    tags: ["regulator"],
    size: { w: 18, d: 11, h: 4 },
    mount: "internal",
    iface: "power",
    signals: [],
    voltage: { min: 1.8, max: 5.5 },
    activeMa: 0,
    sleepUa: 25,
    supplyMa: 800,
    specs: [["Output", "3.3V, up to 800 mA"], ["Input", "1.8–5.5V"], ["Efficiency", "~90%"]],
    pins: [P("VIN", "Battery in", "power"), P("VOUT", "3.3V out", "power"), GND],
    priceInr: 95,
    color: "#55585E",
    icon: "activity",
  }),
  def({
    id: "solar_panel",
    name: "Solar Panel",
    subtitle: "5V 1W",
    role: "Trickle charging",
    category: "power",
    group: "Power",
    description: "Small panel that tops up the battery outdoors.",
    tags: ["solar", "outdoor"],
    size: { w: 60, d: 60, h: 3 },
    mount: "top_external",
    cutout: { shape: "circle", w: 3.5, h: 3.5 },
    iface: "power",
    signals: [],
    voltage: { min: 4.5, max: 6 },
    activeMa: 0,
    sleepUa: 0,
    supplyMa: 200,
    specs: [["Output", "5V, 200 mA in full sun"], ["Size", "60 × 60 mm"], ["Average yield", "~250 mAh/day outdoors"]],
    pins: [P("V+", "Panel positive", "power"), P("V-", "Panel negative", "gnd")],
    priceInr: 210,
    color: "#2F4A7A",
    icon: "sun",
  }),
  def({
    id: "slide_switch",
    name: "Power Switch",
    subtitle: "Slide • On/Off",
    role: "Hard power off",
    category: "power",
    group: "Power",
    description: "Slide switch that fully disconnects the battery.",
    tags: ["power_switch"],
    size: { w: 9, d: 4, h: 4 },
    mount: "front",
    cutout: { shape: "rect", w: 5, h: 2.5 },
    iface: "power",
    signals: [],
    voltage: { min: 0, max: 12 },
    activeMa: 0,
    sleepUa: 0,
    specs: [["Type", "SPDT slide"], ["Rating", "0.3A at 6V"]],
    pins: [P("IN", "From charger", "power"), P("OUT", "To board", "power")],
    priceInr: 12,
    color: "#55585E",
    icon: "toggle-right",
  }),
];

export const BLOCK_MAP: Record<string, BlockDef> = Object.fromEntries(BLOCKS.map((b) => [b.id, b]));
export const getBlock = (id: string): BlockDef | undefined => BLOCK_MAP[id];
export const BLOCK_GROUPS = ["Compute", "Input", "Output", "Connect", "Power"] as const;

export const CATEGORY_LABEL: Record<string, string> = {
  mcu: "MCU",
  sensor: "Sensors",
  connectivity: "Connectivity",
  power: "Power",
  display: "Display",
  audio: "Audio",
  input: "Input",
  output: "Output",
  other: "Other",
};

/** Compact catalogue the model picks from. */
export const catalogForPrompt = (): string =>
  BLOCKS.map(
    (b) =>
      `- ${b.id} | ${b.name} (${b.subtitle}) | ${b.category} | ₹${b.priceInr} | ${b.size.w}×${b.size.d}×${b.size.h}mm | ${b.iface}${b.signals.length ? ` needs ${b.signals.length} pin(s)` : ""} | tags: ${b.tags.join(", ")} | ${b.description}`,
  ).join("\n");
