import { TEMPLATES, compile } from "@craftr/core";
import { assets, blockArt, db } from "@craftr/db";
import { and, asc, eq, like } from "drizzle-orm";
import { Hono } from "hono";
import { cors } from "hono/cors";
import { HTTPException } from "hono/http-exception";
import { hasClaude } from "./ai/claude";
import { hasImages } from "./ai/images";
import { requireUser, type AppEnv } from "./auth";
import { env } from "./env";
import { adminRoutes } from "./routes/admin";
import { orderRoutes } from "./routes/orders";
import { projectRoutes } from "./routes/projects";

export const app = new Hono<AppEnv>();

app.use(
  cors({
    origin: (origin) => (env.webOrigins.includes(origin) || (!env.isProd && /^http:\/\/localhost:\d+$/.test(origin)) ? origin : null),
    allowHeaders: ["authorization", "content-type", "x-dev-user"],
    allowMethods: ["GET", "POST", "PATCH", "DELETE", "OPTIONS"],
    maxAge: 86400,
  }),
);

app.onError((err, c) => {
  if (err instanceof HTTPException) return c.json({ error: err.message }, err.status);
  console.error(err);
  return c.json({ error: err instanceof Error ? err.message : "Something went wrong." }, 500);
});

app.get("/", (c) => c.json({ name: "craftr-api", ok: true }));
app.get("/health", (c) => c.json({ ok: true, db: !!process.env.DATABASE_URL, auth: !!env.clerkSecret, chat: hasClaude(), images: hasImages() }));

app.get("/assets/:id", async (c) => {
  const [a] = await db().select().from(assets).where(eq(assets.id, c.req.param("id")));
  if (!a) return c.json({ error: "Not found" }, 404);
  return c.body(Buffer.from(a.data, "base64"), 200, { "content-type": a.mime, "cache-control": "public, max-age=31536000, immutable" });
});

/** Block art is generated by admins; blocks without art fall back to a drawn tile in the web app. */
app.get("/block-art", async (c) => {
  const rows = await db().select().from(blockArt);
  c.header("cache-control", "public, max-age=30");
  return c.json(Object.fromEntries(rows.map((r) => [r.blockId, r.assetId])));
});

app.get("/templates", async (c) => {
  // Each proven build has one shared render, drawn from its real 3D model.
  const renders = await db().select({ id: assets.id, ref: assets.ref }).from(assets).where(and(eq(assets.kind, "preview"), like(assets.ref, "template:%"))).orderBy(asc(assets.createdAt));
  const byTemplate = Object.fromEntries(renders.map((r) => [r.ref!.slice(9), r.id]));
  c.header("cache-control", "public, max-age=30");
  return c.json(
    TEMPLATES.map((t) => {
      const k = compile(t);
      return { id: t.id, name: t.name, tagline: t.tagline, description: t.description, prompt: t.prompt, features: t.features, blocks: t.nodes.map((n) => n.blockId), design: t.design, shape: k.layout.shape, outer: k.layout.outer, unitInr: k.pricing.unitInr, battery: k.power.batteryLabel, previewAssetId: byTemplate[t.id] ?? null };
    }),
  );
});

app.get("/me", requireUser, (c) => c.json(c.get("user")));
app.route("/projects", projectRoutes);
app.route("/orders", orderRoutes);
app.route("/admin", adminRoutes);
