"use client";

import { useAuth } from "@clerk/nextjs";
import { useQuery } from "@tanstack/react-query";
import { useCallback } from "react";
import type { Me } from "./types";

export const API_URL = (process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:4747").replace(/\/$/, "");
export const assetUrl = (id: string) => `${API_URL}/assets/${id}`;

export class ApiError extends Error {
  constructor(
    message: string,
    public status: number,
  ) {
    super(message);
  }
}

export type Api = <T = unknown>(path: string, init?: { method?: string; body?: unknown }) => Promise<T>;

/** Calls the Craftr api as the signed-in user. */
export function useApi(): Api {
  const { getToken } = useAuth();
  return useCallback(
    async (path, init) => {
      const token = await getToken();
      let res: Response;
      try {
        res = await fetch(`${API_URL}${path}`, {
          method: init?.method ?? (init?.body ? "POST" : "GET"),
          headers: { ...(token ? { authorization: `Bearer ${token}` } : {}), ...(init?.body ? { "content-type": "application/json" } : {}) },
          body: init?.body ? JSON.stringify(init.body) : undefined,
        });
      } catch {
        throw new ApiError("Can't reach the Craftr api. Check your connection and try again.", 0);
      }
      const data = await res.json().catch(() => null);
      if (!res.ok) throw new ApiError(data?.error ?? `Request failed (${res.status})`, res.status);
      return data;
    },
    [getToken],
  );
}

export function useMe() {
  const api = useApi();
  const { isSignedIn } = useAuth();
  return useQuery({ queryKey: ["me"], queryFn: () => api<Me>("/me"), enabled: !!isSignedIn, staleTime: 60_000 });
}

/** Block art generated by admins: blockId -> asset id. Public, so no token needed. */
export function useBlockArt() {
  return useQuery({
    queryKey: ["block-art"],
    queryFn: async () => {
      const res = await fetch(`${API_URL}/block-art`);
      return res.ok ? ((await res.json()) as Record<string, string>) : {};
    },
    staleTime: 60_000,
  }).data;
}

export const errorText = (e: unknown) => (e instanceof Error ? e.message : "Something went wrong.");
